os: osx

language: cpp

compiler:
  - gcc
  
sudo: required

env:
  - TEST_OUTPUT=test_output

script:
  - make test |& tee $TEST_OUTPUT
  - cat $TEST_OUTPUT
  - grep "No errors detected" $TEST_OUTPUT
